"""render_plan — export the engagement plan as CSV files or JSON."""

from __future__ import annotations

from typing import Any, Literal

from pydantic import BaseModel, Field, ValidationError


class RenderPlanArgs(BaseModel):
    format: Literal["csv", "json"] = Field(
        default="csv",
        description="Output format: 'csv' writes two CSV files, 'json' returns the full plan",
    )
    output_dir: str = Field(
        default="",
        description=(
            "Directory for CSV output. Defaults to ~/.open-pharma-plugins/next-best-engagement/. "
            "Ignored for JSON format."
        ),
    )
    plan_json: str = Field(
        default="",
        description=(
            "The engagement plan as a JSON string. If omitted, uses the last plan generated by recommend_engagements."
        ),
    )


TOOL: dict[str, Any] = {
    "name": "render_plan",
    "description": (
        "Export the engagement plan to CSV files or return it as structured "
        "JSON. CSV mode writes two uniquely named artifacts: one with each "
        "planned action and input-universe extra columns, and one with "
        "coverage, utilisation, and channel-mix metrics. Consumers must use "
        "the returned files.engagements_csv and files.summary_csv paths. "
        "Call recommend_engagements first to obtain the plan JSON."
    ),
    "args": RenderPlanArgs,
}


def handle(arguments: dict[str, Any]) -> list[dict[str, Any]]:
    import json
    from pathlib import Path

    from .._renderer import render_csv, render_json
    from .._universe import get_stored_plan
    from ..models import EngagementPlan

    try:
        args = RenderPlanArgs.model_validate(arguments)
    except ValidationError as exc:
        return [{"type": "text", "text": json.dumps({"error": f"Invalid render arguments: {exc}"})}]

    plan_json = args.plan_json.strip()

    if plan_json:
        try:
            plan = EngagementPlan.model_validate_json(plan_json)
        except Exception as e:
            return [{"type": "text", "text": json.dumps({"error": f"Invalid plan JSON: {e}"})}]
        _, universe_fingerprint, universe_generation = get_stored_plan()
        if universe_fingerprint is None:
            return [
                {
                    "type": "text",
                    "text": json.dumps({"error": "No universe loaded. Call load_universe first."}),
                }
            ]
        if plan.universe_fingerprint != universe_fingerprint or plan.universe_generation != universe_generation:
            return [
                {
                    "type": "text",
                    "text": json.dumps({"error": "Plan is stale for the currently loaded universe."}),
                }
            ]
    else:
        plan, universe_fingerprint, universe_generation = get_stored_plan()
        if plan is None:
            return [
                {
                    "type": "text",
                    "text": json.dumps(
                        {"error": "No plan available. Call recommend_engagements first or pass plan_json."}
                    ),
                }
            ]
        if plan.universe_fingerprint != universe_fingerprint or plan.universe_generation != universe_generation:
            return [
                {
                    "type": "text",
                    "text": json.dumps({"error": "Stored plan is stale for the currently loaded universe."}),
                }
            ]

    fmt = args.format

    if fmt == "json":
        return [{"type": "text", "text": render_json(plan)}]

    output_dir = args.output_dir.strip()
    if not output_dir:
        from shared.env import get_env

        output_dir = get_env(
            "OPEN_PHARMA_NBE_OUTPUT_DIR",
            str(Path.home() / ".open-pharma-plugins" / "next-best-engagement"),
        )

    paths = render_csv(plan, output_dir)
    result = {
        "status": "ok",
        "format": "csv",
        "files": paths,
    }
    return [{"type": "text", "text": json.dumps(result, indent=2)}]
